In [1]:
import pickle
import numpy as np

In [2]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [5]:
# Assume user input
test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [4]:
test_input2

array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object)

In [6]:
test_input2

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [7]:
pipe.predict(test_input2)

C:\Users\hp\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\hp\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0])

In [8]:
# easy to handle and we can change the pipeleine without changing this code means modulariy is increase by using the pipeline